import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from 'src/styles/Home.module.css'

import Container from 'src/components/container'
import Hero from 'components/hero'
import eyecatch from 'images/hero.jpeg'
import Beans from 'components/beans'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Hero title={'炭焼珈琲'} subtitle={'1珈琲'} imageOn />
        <Beans />
      </Container>

      <div className={styles.catch}>
        <figure>
          <Image
            src={eyecatch}
            alt=""
            layout="responsive"
            sizes="(min-width: 1152px) 1152px,100vw"
            priority
            placeholder="blur"
          />
        </figure>
        <p className={styles.text}>
          『炭焼』にこだわり
          <br />
          自家焙煎、炭焼珈琲を販売
          <br />
          炭焼特有の香ばしさや
          <br />
          遠赤外線で中までじっくり火を通し
          <br />
          酸化を遅らせて新鮮で美味しく体にも優しい珈琲を販売しております☺︎
          <br />
          1杯のコーヒーを通じて『ホンワカ』出来る時間をご提供いたします
        </p>
      </div>
    </>
  )
}
